name: megaoverflow_radio
description: MegaOverflow Radio - 24/7 Gospel
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.3.1
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.13
  google_fonts: ^6.2.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  url_launcher: ^6.2.5
  google_mobile_ads: ^5.2.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
